version: "2"
services:
    otel-collector:
        image: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:0.15.0
        volumes:
            - ./otel.yaml:/etc/otelcol/config.yaml
        ports:
            - 13133:13133 # health_check extension
            - 4317:4317 # OTLP gRPC receiver
            - 4318:4318 # OTLP http receiver
        environment:
            - DT_API_TOKEN=<api-token>
            - DT_ENDPOINT='https://{your-env-id}.live.dynatrace.com/api/v2/otlp'
